### ISSUE TITLE
policy-rules Roles and ClusterRoles column

### ISSUE THREAD

**Issue by Joseph94m** [alcideio/rbac-tool#37]
**What would you like to be added**:

When performing a 
`rbac-tool policy-rules {serviceAccount}`
I would like to have 2 columns at the end, where for each action it shows from which (cluster)role it gets the right to do it. For example:

![image](https://user-images.githubusercontent.com/40126230/132010682-5b2f7a55-af76-4e02-b3b5-26d7bd5adbbd.png)

**Why is this needed**:
If you want to manage (specifically remove for my case) an action that a SA can perform on a resource, it would be neat to see from which (cluster)roles this service account gets its rights.

**Comment by gadinaor-r7** [comment]
@Joseph94m - thanks for submitting this enhancement request  - does the screen shot suggest you've gone through the effort of implementing this additional functionality?

**Comment by Joseph94m** [comment]
@gadinaor  The screenshot was handcrafted; however, I've worked on this feature a bit today (from the master branch currently tagged at 1.2.1). 

Unrelated: I noticed something a bit odd. The results  of the lookup command are different in the 1.2.0 and the 1.2.1 .The 1.2.0 labels ClusterRoles as Roles when they are used on a namespaced (i.e. with a Rolebinding).

Is the change from 1.2.0 to 1.2.1 intentional or a regression?

![Screenshot 2021-09-06 at 16 07 40](https://user-images.githubusercontent.com/40126230/132229524-aa21c6c3-dfc5-4b72-8a7b-24defcfe4af3.png)


Concerning the feature of adding Roles/ClusterRoles, I have done some work on that and I am happy to say that I got something working although it needs further validations especially to make sure that it doesn't break anything especially in other functions, as I touched [subject_permissions.go](https://github.com/alcideio/rbac-tool/blob/master/pkg/rbac/subject_permissions.go). I didn't see any test packages I could run from the make file.

I've pushed the branch on my fork under [feature/policy-rules-roles](https://github.com/Joseph94m/rbac-tool/tree/feature/policy-rules-roles) if you'd like to view my changes. I will also review the functional aspect with a colleague who will be using this functionality to administrate the cluster.

here is a sample output:

![image](https://user-images.githubusercontent.com/40126230/132311093-0c50ffc5-3497-47ee-bdb1-95c6d2fdcc07.png)


One of the first things you may notice is that there are less lines on the left table than on the right one. This is normal as the results returned by the current rbac-tool policy-rules does have duplicates. In the change I propose, duplicates (defined as having the same permission from multiple (cluster)roles) are compacted.

**Comment by Joseph94m** [comment]
In case you were wondering what the roles and bindings are

Roles:
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: monitoring
  name: chaching
rules:
- apiGroups: ["","extensions", "apps"]
  resources: ["*"]
  verbs: ["get"]
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: accessor2
rules:
- apiGroups: ["","extensions", "apps"]
  resources: ["*"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods", "secrets"]
  verbs: ["get", "watch", "list"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: monitoring
  name: chaching2
rules:
- apiGroups: ["","extensions", "apps"]
  resources: ["*"]
  verbs: ["get"]
```

bindings: we use [rbac-manager](https://rbac-manager.docs.fairwinds.com/introduction/)
```
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: rbac-tester
rbacBindings:
  - name: rbac-tester
    subjects:
      - kind: ServiceAccount
        name: rbac-tester
        namespace: kube-system
    roleBindings:
       - namespace: monitoring
         role: chaching
       - namespace: monitoring
         role: chaching2
       - namespace: default
         role: chaching2
       - clusterRole: accessor2
         namespace: default
       - clusterRole: accessor2
         namespace: monitoring
       - clusterRole: cluster-admin
         namespace: monitoring 
    clusterRoleBindings:
      - clusterRole: cluster-admin
      - clusterRole: accessor2
```
